export const statusList = [
    "Без статуса",
    "Нужно сделать",
    "В работе",
    "Тестирование",
    "Готово",
  ];

export const cardList = [
    {
        id: 1,
        topic: "Web Design",
        title: "Название задачи",
        date: "30.10.23",
        status: statusList[0],
    },
    {
        id: 2,
        topic: "Recearch",
        title: "Название задачи",
        date: "30.10.23",
        status: statusList[0],
    },
    {
        id: 3,
        topic: "Web Design",
        title: "Название задачи",
        date: "30.10.23",
        status: statusList[0],
    },
    {
        id: 4,
        topic: "Copywriting",
        title: "Название задачи",
        date: "30.10.23",
        status: statusList[0],
    },
    {
        id: 5,
        topic: "Recearch",
        title: "Название задачи",
        date: "30.10.23",
        status: statusList[0],
    },
    {
        id: 6,
        topic: "Recearch",
        title: "Название задачи",
        date: "30.10.23",
        status: statusList[1],
    },
    {
        id: 7,
        topic: "Recearch",
        title: "Название задачи",
        date: "30.10.23",
        status: statusList[2],
    },
    {
        id: 8,
        topic: "Copywriting",
        title: "Название задачи",
        date: "30.10.23",
        status: statusList[2],
    },
    {
        id: 9,
        topic: "Web Design",
        title: "Название задачи",
        date: "30.10.23",
        status: statusList[2],
    },
    {
        id: 10,
        topic: "Recearch",
        title: "Название задачи",
        date: "30.10.23",
        status: statusList[3],
    },
    {
        id: 11,
        topic: "Recearch",
        title: "Название задачи",
        date: "30.10.23",
        status: statusList[4],
    },
]